# Generated by Django 2.2.4 on 2019-08-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_pay', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
