# Generated by Django 2.2.4 on 2019-09-04 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_pay', '0004_auto_20190904_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_channel',
            name='pay_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt', to='pay.Payment_type', verbose_name='对应的支付总类型'),
        ),
        migrations.AlterField(
            model_name='payment_channel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='pay.Payment_vendor', verbose_name='对应的厂商'),
        ),
    ]
