# Generated by Django 2.2.4 on 2019-09-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_pay', '0005_auto_20190904_0825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment_channel',
        ),
        migrations.DeleteModel(
            name='Payment_type',
        ),
        migrations.DeleteModel(
            name='Payment_vendor',
        ),
    ]
