# Generated by Django 2.2.4 on 2019-09-09 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkNo', models.CharField(max_length=255, verbose_name='用户id')),
                ('username', models.CharField(max_length=500, verbose_name='用户名')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('balance', models.FloatField(verbose_name='用户钱包')),
            ],
        ),
        migrations.CreateModel(
            name='AccountChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=500, verbose_name='交易记录')),
                ('orderid', models.CharField(max_length=500, verbose_name='订单号')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('status', models.BooleanField(default=True, verbose_name='订单状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='game.User', verbose_name='用户')),
            ],
        ),
    ]
