# Generated by Django 2.2.4 on 2019-09-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountchange',
            old_name='orderid',
            new_name='orderNum',
        ),
        migrations.AddField(
            model_name='accountchange',
            name='vendor_orderNum',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='厂商订单号'),
        ),
    ]
