# Generated by Django 2.2.4 on 2019-09-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_game', '0002_auto_20190910_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorId', models.CharField(blank=True, max_length=255, null=True)),
                ('gameKindId', models.CharField(blank=True, max_length=255, null=True)),
                ('gameCode', models.CharField(blank=True, max_length=255, null=True, verbose_name='游戏代码')),
                ('gameName', models.CharField(max_length=255, verbose_name='游戏名')),
                ('gameStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('pc', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('pictureUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('lang', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.CharField(max_length=255)),
                ('updatedAt', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.CharField(blank=True, max_length=255, null=True)),
                ('vendorCode', models.CharField(max_length=255)),
                ('vendorName', models.CharField(max_length=255)),
                ('gameKindCode', models.CharField(max_length=255)),
                ('gameKindName', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='种类代码')),
                ('name', models.CharField(max_length=255, verbose_name='游戏名')),
                ('lang_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='游戏英文名')),
                ('lang_zh', models.CharField(blank=True, max_length=255, null=True, verbose_name='游戏中文名')),
                ('creator', models.CharField(max_length=255, verbose_name='创建者')),
                ('createAt', models.CharField(blank=True, max_length=255, null=True)),
                ('updateAt', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='accountchange',
            name='user_balance',
            field=models.FloatField(null=True, verbose_name='用户当前余额'),
        ),
        migrations.AlterField(
            model_name='accountchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='game.User', verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='GameVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorName', models.CharField(max_length=255, verbose_name='游戏厂商')),
                ('vendorCode', models.CharField(max_length=255, verbose_name='厂商编码')),
                ('gameKindName', models.CharField(max_length=255, verbose_name='游戏名')),
                ('gameKindCode', models.CharField(max_length=255, verbose_name='游戏码')),
                ('pictureUrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片地址')),
                ('hallUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gameType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='game.GameType', verbose_name='厂商的游戏类型')),
            ],
        ),
        migrations.AddField(
            model_name='accountchange',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.GameVendor', verbose_name='厂商'),
        ),
    ]
