# Generated by Django 2.2.4 on 2019-09-12 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_game', '0004_gamevendor_gamealias'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkNo', models.CharField(max_length=255, verbose_name='用户id')),
                ('balance', models.CharField(max_length=255, verbose_name='用户余额')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.AlterField(
            model_name='accountchange',
            name='user_balance',
            field=models.FloatField(default=0, verbose_name='用户当前余额'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountchange',
            name='vendor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='game.GameVendor', verbose_name='厂商'),
            preserve_default=False,
        ),
    ]
