# Generated by Django 2.2.4 on 2019-09-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_game', '0005_auto_20190912_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountchange',
            name='user_balance',
        ),
        migrations.RemoveField(
            model_name='accountchange',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='accountchange',
            name='vendor_orderNum',
        ),
        migrations.AddField(
            model_name='accountchange',
            name='after_balance',
            field=models.FloatField(default=0, verbose_name='操作后余额'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountchange',
            name='befor_balance',
            field=models.FloatField(default=0, verbose_name='操作前余额'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountchange',
            name='game_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='游戏代码'),
        ),
        migrations.AddField(
            model_name='accountchange',
            name='vendor_code',
            field=models.CharField(default=0, max_length=255, verbose_name='厂商代码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='balance',
            field=models.FloatField(verbose_name='用户余额'),
        ),
    ]
