# Generated by Django 2.2.4 on 2019-09-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_game', '0006_auto_20190912_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountchange',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='厂商代码'),
        ),
    ]
